[workspace]
resolver = "2"
members = [
    "backend",
    "sourc-code/tui",
    "source-code/gui",
]

[workspace.dependencies]
tokio       = { version = "1", features = ["full"] }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
anyhow      = "1"
thiserror   = "1"
tracing     = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest     = { version = "0.12", features = ["json", "stream", "multipart"] }
axum        = { version = "0.7", features = ["multipart"] }
tower-http  = { version = "0.5", features = ["cors", "fs"] }
uuid        = { version = "1", features = ["v4"] }
chrono      = { version = "0.4", features = ["serde"] }
bytes       = "1"
futures     = "1"
async-stream = "0.3"
